In [1]:
import torch

In [2]:
x = torch.tensor([[1., 2.], [3., -4.]])


x * x

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [51]:
# Convert pickle to feather.
import pyarrow.feather as feather
import pickle
import pandas as pd
import os 



keys = [
  'p_mean',
  'pet_mean',
  'p_seasonality',
  'frac_snow',
  'aridity',
  'high_prec_freq',
  'high_prec_dur',
  'low_prec_freq',
  'low_prec_dur',
  'elev_mean',
  'slope_mean',
  'area_gages2',
  'frac_forest',
  'lai_max',
  'lai_diff',
  'gvf_max',
  'gvf_diff',
  'dom_land_cover_frac',
  'dom_land_cover',
  'root_depth_50',
  'soil_depth_pelletier',
  'soil_depth_statsgo',
  'soil_porosity',
  'soil_conductivity',
  'max_water_content',
  'sand_frac',
  'silt_frac',
  'clay_frac',
  'geol_1st_class',
  'glim_1st_class_frac',
  'geol_2nd_class',
  'glim_2nd_class_frac',
  'carbonate_rocks_frac',
  'geol_porosity',
  'geol_permeability'
]

# Path to the pickle file
file_path = '/data/lgl5139/datasets/training_file_tempral_1980_2014_whole_time_period_Acuna'
feather_path = '/data/lgl5139/datasets/acuna_1980_2014/attr_acuna_531_1980_2014.feather'

# Open and load the pickle file
with open(file_path, 'rb') as file:
    data = pickle.load(file)

df = pd.DataFrame()
for i, key in enumerate(keys):
    # flattened_list = [item for sublist in data[2][:,i] for item in sublist]
    # print(len(flattened_list))
    df[key] = data[2][:,i].tolist()

# Save the DataFrame to a Feather file
df.to_feather(feather_path)

In [53]:
df

p_mean  pet_mean  p_seasonality  frac_snow   aridity  high_prec_freq  \
0    3.608126  2.119256      -0.114530   0.245259  0.587356           20.55   
1    3.522957  2.071324       0.104091   0.291836  0.587950           18.90   
2    3.323146  2.090024       0.147776   0.280118  0.628929           20.10   
3    3.730858  2.096423       0.152097   0.352698  0.561914           13.50   
4    4.067132  2.128355       0.104960   0.299642  0.523306           17.50   
..        ...       ...            ...        ...       ...             ...   
526  4.977781  3.122204      -0.995847   0.061255  0.627228           15.10   
527  4.543400  2.277630      -0.821172   0.176337  0.501305           14.75   
528  6.297437  2.434652      -0.952055   0.030203  0.386610           14.60   
529  2.781676  3.325188      -0.985486   0.141500  1.195390           20.45   
530  5.556071  2.279668      -1.015946   0.024330  0.410302           19.30   

     high_prec_dur  low_prec_freq  low_prec_dur  elev_mean  ...  sand_frac  \
0         1.205279         233.65      3.662226      92.68  ...  59.390156   
1         1.148936         227.35      3.473644     247.80  ...  35.269030   
2         1.165217         235.90      3.691706     310.38  ...  55.163133   
3         1.129707         193.50      2.896707     615.70  ...  30.557666   
4         1.194539         220.30      3.263704     472.31  ...  58.376169   
..             ...            ...           ...        ...  ...        ...   
526       1.776471         222.65      6.893189     709.83  ...  37.751217   
527       1.446078         214.85      6.018207     952.26  ...  37.238495   
528       1.467337         219.05      6.240741     656.53  ...  38.961578   
529       1.786026         260.35      7.354520     875.67  ...  37.914394   
530       1.537849         237.00      6.909621     625.31  ...  30.026587   

     silt_frac  clay_frac  geol_1st_class  glim_1st_class_frac  \
0    28.080937  12.037646             0.0             0.590658   
1    50.841232  12.654125            10.0             0.448928   
2    34.185443  10.303622             7.0             0.308488   
3    52.614646  11.143326            10.0             0.497458   
4    31.836472   9.851262             7.0             0.871443   
..         ...        ...             ...                  ...   
526  38.879406  23.213862            10.0             0.863563   
527  38.519396  24.363634             3.0             0.444680   
528  40.860260  20.068726            10.0             0.903702   
529  39.602460  22.404372             3.0             0.983481   
530  42.214515  27.805122            10.0             0.606239   

     geol_2nd_class  glim_2nd_class_frac  carbonate_rocks_frac  geol_porosity  \
0              10.0             0.164618              0.000000         0.0710   
1               7.0             0.443863              0.026258         0.0747   
2               0.0             0.288613              0.000000         0.0522   
3               7.0             0.374062              0.000000         0.0711   
4              10.0             0.104295              0.000000         0.0288   
..              ...                  ...                   ...            ...   
526             3.0             0.095225              0.000000         0.1731   
527             8.0             0.373506              0.000000         0.1338   
528             2.0             0.062996              0.000000         0.1708   
529             0.0             0.016519              0.000000         0.0887   
530             2.0             0.288975              0.000000         0.1216   

     geol_permeability  
0             -14.2138  
1             -14.8410  
2             -14.4819  
3             -15.1658  
4             -14.2147  
..                 ...  
526           -14.8976  
527           -13.5958  
528           -15.1799  
529           -12.5264  
530           -14.7163  

[531 rows x 35 columns]

In [55]:
data[0].squeeze().shape


(531, 12418, 3)

In [6]:
array_list = data[0]tolist()
flattened_list = [item for sublist in array_list for item in sublist]
flattened_list

[2.054303, 2.045786, 2.093596, 1.6305056]

In [30]:
data[1].squeeze()[:2,:]

array([[224., 190., 171., ...,  48.,  46.,  46.],
       [175., 157., 163., ...,  nan,  nan,  nan]])

In [46]:
# Convert pickle to feather.
import pyarrow.feather as feather
import pandas as pd

dict = [  
    'prcp',
    'tmean',
    'pet'
    ]

# Replace 'your_file.feather' with the path to your Feather file.
file_path = '/data/lgl5139/datasets/acuna_1980_2014/attr_acuna_531_1980_2014.feather'

# Read the Feather file into a pandas DataFrame.
df = feather.read_feather(file_path)

# Display the DataFrame
print(df)


      p_mean pet_mean p_seasonality frac_snow   aridity high_prec_freq  \
0    [224.0]  [190.0]       [171.0]   [316.0]   [457.0]        [420.0]   
1    [175.0]  [157.0]       [163.0]   [493.0]   [900.0]        [615.0]   
2    [148.0]  [140.0]       [146.0]   [263.0]   [457.0]        [344.0]   
3    [172.0]  [158.0]       [458.0]  [1100.0]  [1020.0]        [531.0]   
4     [20.0]   [19.0]        [32.0]   [161.0]    [96.0]         [54.0]   
..       ...      ...           ...       ...       ...            ...   
526    [nan]    [nan]         [nan]     [nan]     [nan]          [nan]   
527    [nan]    [nan]         [nan]     [nan]     [nan]          [nan]   
528    [nan]    [nan]         [nan]     [nan]     [nan]          [nan]   
529    [nan]    [nan]         [nan]     [nan]     [nan]          [nan]   
530    [nan]    [nan]         [nan]     [nan]     [nan]          [nan]   

    high_prec_dur low_prec_freq low_prec_dur elev_mean  ... sand_frac  \
0         [384.0]       [331.0]      [

In [47]:
data[2][:,0]

array([3.60812594, 3.52295688, 3.32314579, 3.73085832, 4.0671321 ,
       3.49418344, 3.57049966, 3.50302533, 3.56288843, 3.8242423 ,
       3.46741273, 3.98419165, 3.13454757, 3.3035154 , 3.31467077,
       3.42085969, 3.78353457, 3.92116632, 3.89458179, 3.81502396,
       3.9506078 , 3.68248186, 3.70463929, 3.86979603, 3.49282546,
       3.50142231, 4.211436  , 3.17544969, 3.8325462 , 3.97997125,
       3.77312252, 3.70376044, 4.43700205, 4.31765366, 3.68325804,
       3.54989322, 3.75335113, 3.50320739, 3.5398371 , 3.3212731 ,
       3.33903901, 3.30507598, 3.46229432, 3.18264339, 3.03164134,
       3.19507871, 3.42342779, 3.42252841, 3.39001916, 3.4089295 ,
       3.36351951, 3.38457495, 3.135013  , 3.15334565, 3.33222587,
       3.36976591, 3.47699795, 3.62308556, 3.15309925, 3.21283915,
       3.32970157, 3.43172758, 3.26212594, 3.30466119, 3.28500616,
       3.92110335, 3.31426557, 3.20968925, 3.36347707, 2.93104038,
       2.90811225, 2.97918001, 3.034423  , 3.23323888, 3.04764

In [24]:
import pandas as pd
import numpy as np


path = '/data/yxs275/CONUS_data/conus_merit/attr/region_2.csv'
df = pd.read_csv(path)

path = '/data/yxs275/CONUS_data/conus_merit/forcing/region_2.npy'
dat = np.load(path)

In [2]:
df.keys()

Index(['Unnamed: 0', 'aridity', 'meanP', 'ETPOT_Hargr', 'NDVI', 'FW',
       'meanslope', 'SoilGrids1km_sand', 'SoilGrids1km_clay',
       'SoilGrids1km_silt', 'glaciers', 'HWSD_clay', 'HWSD_gravel',
       'HWSD_sand', 'HWSD_silt', 'meanelevation', 'meanTa', 'permafrost',
       'permeability', 'seasonality_P', 'seasonality_PET', 'snow_fraction',
       'snowfall_fraction', 'T_clay', 'T_gravel', 'T_sand', 'T_silt',
       'Porosity', 'catchsize'],
      dtype='object')

In [4]:
df['aridity']

0       2.541012
1       0.828147
2       1.041834
3       0.788433
4       4.154153
          ...   
4995    0.890712
4996    3.043192
4997    0.906874
4998    0.872546
4999    3.297616
Name: aridity, Length: 5000, dtype: float64

In [28]:
dat[0].size

44928

In [26]:
44928/3

14976.0

In [16]:
"""
Code to support the processing of CONUS files in non-feather formats until full
support is offered in the PMI.

Adapted from Yalan Song 2024.
"""
import numpy as np
import pandas as pd
import json



### Debug
config = []
data_dir = '/data/yxs275/CONUS_data/FromGAGEII/generate_for_CONUS_3200/gages/dataCONUS3200/'
shape_id_path = '/data/yxs275/CONUS_data/FromGAGEII/generate_for_CONUS_3200/shapeID_str_lst.npy'
attr_path = '/data/yxs275/CONUS_data/attributes/CONUS_3254/attributes_haoyu/attributes_haoyu.csv'
gage_info_path = '/data/yxs275/CONUS_data/CONUS_for_NH_training/gages_3000_merit_info.csv'
area_info = ''
merit_idx = ''
###


# load_conus(
#     config,
#     data_folder,
#     attributes,
#     shape_ids,
#     gage_info
# )

## TODO: replace pd implementation with config date ranges:
time = pd.date_range('1980-10-01',f'1995-09-30', freq='d')

with open(data_dir + 'train_data_dict.json') as f:
    train_data_dict = json.load(f)

full_period = pd.date_range('1980-01-01', f'2020-12-31', freq='d')
ind_start = full_period.get_loc(time[0])
ind_end = full_period.get_loc(time[-1])


# Load shape id list, target streamflow observations, attributes, forcings,
# and merit gage info.
shape_id_lst = np.load(shape_id_path)
streamflow = np.load(data_dir + 'train_flow.npy')

all_attributes = pd.read_csv(attr_path,index_col=0)
all_attributes = all_attributes.sort_values(by='id')

merit_gage_info = pd.read_csv(gage_info_path) 
merit_gage_info = merit_gage_info.sort_values(by='STAID')
gage_ids = merit_gage_info['STAID'].values    

# Only keep data for gages we want.
all_attributes = all_attributes[all_attributes['id'].isin(gage_ids)]
all_attributes_list = all_attributes.columns



## Get basin area for unit conversions.
basin_area = np.expand_dims(all_attributes["area"].values,axis = 1)

lat =  all_attributes["lat"].values
id_list_new = all_attributes["id"].values
id_list_old = [int(id) for id in shape_id_lst]
[c, ind_1, sub_ind] = np.intersect1d(id_list_new, id_list_old, return_indices=True)
key_info = [str(x) for x in id_list_new]


# Only keep data for gages we want.
streamflow = streamflow[sub_ind,:,:]
if(not (id_list_new==np.array(id_list_old)[sub_ind]).all()):
    raise Exception("Ids of subset gage do not match with ids in the attribute file.")





attribute_list = ['ETPOT_Hargr', 'FW', 'HWSD_clay', 'HWSD_gravel', 'HWSD_sand',
       'HWSD_silt', 'NDVI', 'Porosity', 'SoilGrids1km_clay',
       'SoilGrids1km_sand', 'SoilGrids1km_silt', 'T_clay', 'T_gravel',
       'T_sand', 'T_silt', 'aridity', 'glaciers', 'meanP', 'meanTa',
       'meanelevation', 'meanslope', 'permafrost', 'permeability',
       'seasonality_P', 'seasonality_PET', 'snow_fraction',
       'snowfall_fraction']

attribute_list_water_loss = attribute_list.copy()
attribute_list_water_loss.append('uparea')
attribute_list_old = attribute_list.copy()


forcing_list_water_loss = ['P','Temp','PET']





with open('/projects/mhpi/yxs275/tools/extrect_merit_in_basin/'+'area_info.json') as f:
    area_info = json.load(f)

save_path_merit_path = '/projects/mhpi/yxs275/Data/merit_data_in_gages_3000_merit_filled_train/CONUS2800'

with open('/projects/mhpi/yxs275/Data/merit_data_in_gages_3000_merit_filled_train/' + 'merit_idx.json') as f:
    merit_idx = json.load(f)

In [37]:
import pickle

streamflow

array([[[1140. ],
        [1080. ],
        [1050. ],
        ...,
        [ 362. ],
        [ 327. ],
        [ 307. ]],

       [[ 509. ],
        [ 518. ],
        [ 516. ],
        ...,
        [  54. ],
        [  50. ],
        [  49. ]],

       [[ 802. ],
        [ 774. ],
        [ 764. ],
        ...,
        [  51. ],
        [  52. ],
        [  51. ]],

       ...,

       [[1100. ],
        [1100. ],
        [1100. ],
        ...,
        [1920. ],
        [1950. ],
        [2060. ]],

       [[  33.5],
        [  32.5],
        [  31.5],
        ...,
        [  37. ],
        [  41. ],
        [  45. ]],

       [[  65. ],
        [  62. ],
        [  60. ],
        ...,
        [ 216. ],
        [ 188. ],
        [ 138. ]]])

In [23]:
with open('/data/yxs275/CONUS_data/CONUS_for_NH_training/CONUS2800_test.pkl', 'rb') as file:
    data = pickle.load(file)



In [40]:
np.load("/data/yxs275/CONUS_data/FromGAGEII/generate_for_CONUS_3200/allBasin_localDaymet.npy")

array([[[  0.        ,  -5.15675449, -17.85018349],
        [  0.        ,  -6.46068382, -11.97346115],
        [  0.        , -10.78380489, -19.93343735],
        ...,
        [  0.        ,  -6.44053936, -11.28903961],
        [ 14.52318096,  -1.68931329, -12.75347614],
        [         nan,          nan,          nan]],

       [[  0.        ,  -6.32506323, -16.47676659],
        [  0.        ,  -6.18539762, -15.4323473 ],
        [  0.        , -11.94784164, -18.82919693],
        ...,
        [  0.        ,  -1.66033506, -10.83742237],
        [  6.63147211,  -3.85107255, -12.59798336],
        [         nan,          nan,          nan]],

       [[  0.        ,  -5.01582193, -16.47083855],
        [  0.        ,  -5.31965065, -12.8223362 ],
        [  0.        , -10.84102154, -17.79621506],
        ...,
        [  0.        ,  -1.54956019, -10.13127518],
        [  8.75255585,  -2.64309907, -12.04709053],
        [         nan,          nan,          nan]],

       ...,

      

In [41]:
pd.read_csv('/data/yxs275/CONUS_data/FromGAGEII/generate_for_CONUS_3200/gage_id.csv').keys()

Index(['GAUGE_ID'], dtype='object')

In [42]:
with open('/data/yxs275/CONUS_data/FromGAGEII/generate_for_CONUS_3200/gages/dataCONUS3200/train_data_dict.json', 'r') as file:
    data = json.load(file)

In [49]:
data['constant_cols']

['PPTAVG_BASIN',
 'LAT_GAGE',
 'LNG_GAGE',
 'DRAIN_SQKM',
 'ELEV_MEAN_M_BASIN',
 'SLOPE_PCT',
 'DEVNLCD06',
 'FORESTNLCD06',
 'PLANTNLCD06',
 'WATERNLCD06',
 'SNOWICENLCD06',
 'BARRENNLCD06',
 'SHRUBNLCD06',
 'GRASSNLCD06',
 'WOODYWETNLCD06',
 'EMERGWETNLCD06',
 'AWCAVE',
 'PERMAVE',
 'RFACT',
 'ROCKDEPAVE',
 'GEOL_REEDBUSH_DOM',
 'GEOL_REEDBUSH_DOM_PCT',
 'STREAMS_KM_SQ_KM',
 'NDAMS_2009',
 'STOR_NOR_2009',
 'RAW_DIS_NEAREST_MAJ_DAM',
 'CANALS_PCT',
 'RAW_DIS_NEAREST_CANAL',
 'FRESHW_WITHDRAWAL',
 'POWER_SUM_MW',
 'PDEN_2000_BLOCK',
 'ROADS_KM_SQ_KM',
 'IMPNLCD06']